baseURL = ""
title = "弥罗"
theme = "minimal-chinese"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
relativeURLs = true
uglyURLs = false

[params]
  description = "博客，技术，随想，极简，新中式"
  author = "太一"
  paginate = 6
  keywords = ["博客", "技术", "随笔", "思考", "极简", "新中式"]

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/post/:year/:month/:day/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.zh-cn]
    languageCode = "zh-CN"
    languageName = "Chinese"
    weight = 1