baseURL = "/"
languageCode = "zh-CN"
title = "弥罗"
theme = "minimal-chinese"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
googleAnalytics = ""

[params]
  description = "极简，新中式，博客，技术，随想"
  author = "太一"
  paginate = 4
  keywords = ["博客", "技术", "极简", "新中式", "随笔", "思考"]

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/post/:year/:month/:day/:slug/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false